# noinspection YAMLSchemaValidation
main: ${groupId}.${name}
version: ${version}
# noinspection YAMLSchemaValidation
name: ${name}
api-version: ${api-version}
description: ${description}
authors: [ JBouchier, TheMrJezza ]
website: https://www.spigotmc.org/resources/horsetpwithme.8186/
commands:
  Reseat:
    description: "Reseat yourself on your vehicle!"
    permission: horsetpwithme.command.reseat
  TeleportAsPassenger:
    description: "Toggle your T.A.P. Status. If disabled, you cannot teleport as a passenger."
    usage: /<command>
    aliases:
      - taptoggle
  HorseDebug:
    description: "Toggle Debug Stuff"
    permission: horsetpwithme.command.horsedebug
    usage: /<command>