name: HorseTpWithMe
main: com.jbouchier.horsetpwithme.HorseTpWithMe
version: 10
api-version: 1.17
description: "Like your horse? Now you won't teleport without it!"
website: https://www.spigotmc.org/resources/horsetpwithme.8186/
author: "Jeremy Bouchier (Aka: TheMrJezza)"
commands:
  horsetpwithme:
    permission: horsetpwithme.commands.htwm
    description: Main Command for All HorseTpWithMe stuff.
    usage: /<command> < reload | getperm >
    aliases:
      - htwm
      - htpwm
  TeleportAsPassenger:
    description: Toggle Your Teleport-As-Passenger status.
    usage: /<command>
    aliases:
      - taptoggle
permissions:
  horsetpwithme.*:
    default: op
    children:
      horsetpwithme.teleport.*: true
      horsetpwithme.messages.*: true
      horsetpwithme.commands.*: true
  horsetpwithme.messages.*:
    default: op
    description: All messages will be visible!
  horsetpwithme.commands.*:
    description: Use any HorseTpWithMe command!
    default: op
    children:
      horsetpwithme.commands.htwm: true
  horsetpwithme.commands.htwm:
    description: Grants access to /horsetpwithme
    default: op
  horsetpwithme.require_saddle:
    description: Entities that can have a saddle, must have a saddle to teleport.
    default: false
  horsetpwithme.require_adult:
    description: Unable to teleport Baby Animals.
    default: false
  horsetpwithme.require_tamed:
    default: false
    description: Unable to teleport non-tame animals.
  horsetpwithme.deny_passenger_teleport:
    description: Prevent Teleporting as a Passenger
    default: false
  horsetpwithme.deny_cross_world:
    description: Prevent Teleporting vehicles outside the world they're in.
    default: not op
  horsetpwithme.teleport_passengers:
    default: true
    description: Teleport Passengers with you!
