name: HorseTpWithMe
main: com.jbouchier.horsetpwithme.HorseTpWithMe
version: "10"
api-version: 1.18
description: "Like your horse? Now you won't teleport without it!"
website: https://www.spigotmc.org/resources/horsetpwithme.8186/
author: "Jeremy Bouchier (Aka: TheMrJezza)"
commands:
  horsetpwithme:
    permission: horsetpwithme.commands.htwm
    description: Main Command for All HorseTpWithMe stuff.
    usage: /<command> < reload | getperm >
    aliases:
      - htwm
      - htpwm
  TeleportAsPassenger:
    description: Toggle Your Teleport-As-Passenger status.
    usage: /<command>
    aliases:
      - taptoggle
permissions:
  horsetpwithme.*:
    default: op
    children:
      horsetpwithme.teleport.*: true
      horsetpwithme.messages.*: true
      horsetpwithme.commands.*: true
  horsetpwithme.teleport.*:
    default: true
    description: Teleport anything you can ride!
  horsetpwithme.messages.*:
    default: op
    description: All messages will be visible!
  horsetpwithme.commands.*:
    description: Use any HorseTpWithMe command!
    default: op
    children:
      horsetpwithme.commands.htwm: true
  horsetpwithme.commands.htwm:
    description: Grants access to /horsetpwithme
    default: op