main: "net.horsetpwithme.HorseTpWithMe"
name: "HorseTpWithMe"
version: ${project.version}
authors: [ JBouchier, TheMrJezza ]
softdepend:
  - LeadTheWay
  - Telentity
website: https://www.spigotmc.org/resources/horsetpwithme.8186/
api-version: "1.18"